# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM' do

inhibit_all_warnings!

pod 'AFNetworking'
pod 'MJExtension'
pod 'SDWebImage'
pod 'Masonry'

end
